### ISSUE TITLE
WeaponRealizer.dll seems missing

### ISSUE THREAD

**Issue by bozephalus** [janxious/BT-WeaponRealizer#10]
After downloading and unzipping the addon - loading brings the following message in the ModTek.log

WeaponRealizer 0.5.0
	WeaponRealizer has a DLL specified (C:\Games\SteamLibrary\steamapps\common\BATTLETECH\Mods\BT-WeaponRealizer-master\WeaponRealizer.dll), but it's missing! Aborting load.

**Comment by janxious** [comment]
I can tell from the message you downloaded the wrong file. Use the zip named "WeaponRealizer-v0.5.0.zip" from the releases page. If that doesn't clear up the problem, re-open this ticket.
