### ISSUE TITLE
performace hit since with 1.4 and 1.5

### ISSUE THREAD

**Issue by unclecid** [janxious/BT-WeaponRealizer#13]
with BT versions 1.4 and 1.5 weapon realizer is causing severe slideshow issues in combat.
without WR i get 30 to 60 fps depending on whats happening.
with WR it will drop to single digits and  stutter especially with missile fire

**Comment by janxious** [comment]
I'm not really modding for BT any more. You might ask around on the BTG discord for anyone who might have ideas about this.
