### ISSUE TITLE
Stopping AI from firing AC cannons when refire is too high or to hit chances are below a certain percentage like 35-25%

### ISSUE THREAD

**Issue by xeryx01** [janxious/BT-WeaponRealizer#6]

**Comment by janxious** [comment]
I don't understand the issue. This isn't an AI mod.

**Comment by xeryx01** [comment]
I understand that, you can just delete it. I was hoping there was a way to prevent the AI from being stupid with recoil. But I guess like heat it must be taught elsewhere.  Thanks for all your hard work, and The realizer is fantastic!!

**Comment by xeryx01** [comment]
Can you explain how this works better in the directions?  Is this an additional multiplier of the Variance in the .def file?
        "standardDeviationPercentOfSimpleVariance": 50,
